[tool.poetry]
name = "inverspyctrometry"
version = "0.1.0"
description = "Multiple-beam Interference Spectroscopy: Instrument Analysis and Spectrum Reconstruction"
authors = ["Mohamad Jouni <mhmd.jouni@hotmail.com>"]
license = "MIT"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10, <3.13"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
